### ISSUE TITLE
AttributeError: TIFF_d32f

### ISSUE THREAD

**Issue by lj512lj512** [sentinel-hub/water-observatory-backend#5]
Thank you for providing the nice code. I tried to run the example and I got this issue. Do you have any ideas of what happened?

**Comment by batic** [comment]
Hi,

Unfortunately, the code in this repo has not been updated for quite some time, and some things (like `TIFF_d32f`) have been removed from the Sentinel-Hub service (and newer versions of `sentinelhub-py` package)

We have the update of the code planned, but not in the near future. Pull requests are very much appreciated, though.

**Comment by lj512lj512** [comment]
Hi batic,

thank you for your time and kindly replay, I have fixed it by change TIFF_d32f to TIFF. It worked but some other issues appeared. I would like to keep trying. Thank you.
