### ISSUE TITLE
Updated Code

### ISSUE THREAD

**Issue by taiga2002** [sentinel-hub/water-observatory-backend#6]
Hi, I realized that the current code in Example folder has a lot of outdated library/function that I had to either delete or add some parts of the current code, and now the water detection is not working correctly. 
If there is the most updated code and share, that would be great.

**Comment by batic** [comment]
Hi @taiga2002 

Unfortunately at this point we have no outlook to update / share the code. Feel free to contribute to the project with a pull request.

Best regards,
Matej
